# Generated by Django 5.0 on 2023-12-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_cart', 'Can view cart'), ('add_to_cart', 'Can add items to cart'), ('remove_from_cart', 'Can remove items from cart'), ('update_cart', 'Can update cart'), ('clear_cart', 'Can clear cart'), ('checkout', 'Can proceed to checkout'), ('view_order_history', 'Can view order history'), ('view_product_details', 'Can view product details')),
            },
        ),
    ]
